### PR TITLE
fix(deps): #553 breaking changes in Normalizr 3.5 (v2)

### LINKED ISSUE #553: Update Normalizr
Normalizr 3.5.0 is out but if we update, test fails. Haven't looked into it yet but we need to fix it.

### PR DESCRIPTION
**Pull request by cuebit**
Fixes breaking changes introduced in core dependency Normalizr 3.5.0 (as discussed in #553).

Additionally fixes reference issues (mentioned in #516, and PR #564).

resolves #553, #516
closes #564

### CODE REVIEW

**Comment by kiaking** [comment]
@cuebit Very nice! Let's merge this one. Is this built on top of #564? Then maybe we should first merge #564, then rebase this PR to the latest, and merge (to keep contribution history maybe)?

**Comment by cuebit** [comment]
The fix in this commit related to #564 was made prior to that PR. I think this was just committed at a much later date but seemed appropriate to include it. 

I agree that #564 should be merged to keep contribution history as I wouldn’t want to take away from contributions coming in first. 

The clone deep in this commit increases performance by around 4,000 ops so it will work in favour of large data sets, but also is type safe. We can rebase after.

**Comment by kiaking** [comment]
OK Great. I'llm ere that one first! Please rebase this one after that 👍

**Comment by kiaking** [comment]
And now #564 is merged now.

**Comment by cuebit** [comment]
Rebased. Checks complete. Tests pass. Coverage 100%.

@kiaking ready for orders, captain.

**Comment by kiaking** [comment]
@cuebit Thanks a bunch! But, seems like it has conflict!? Could you fix this one as well 😅

**Comment by cuebit** [comment]
@kiaking conflicts resolved!

**Comment by kiaking** [comment]
Woo hoo!

**Comment by cuebit** [comment]
> Woo hoo!

Hold fire. Feature creep!! An unrelated commit has made it's way in. Let me fix.

**Comment by kiaking** [comment]
Oh OK. I'll wait.

**Comment by cuebit** [comment]
@kiaking OK phew. Done.

This is the last fork commit, thankfully!

**Comment by kiaking** [comment]
Nice! 👍

**Pull request merged**
