### PR TITLE
Update relationships documentation with HasOneBy description

### PR DESCRIPTION
**Pull request by JasonLandbridge**
Added a HasOneBy description to the relationships documentation.
Also re-ordered the documentation text to be the same order as the index.

### CODE REVIEW

**Comment by JasonLandbridge** [comment]
This is based on the following issue and the solution there in: https://github.com/vuex-orm/vuex-orm/issues/51

It took me ages to figure it out and @kiaking talked about adding this to the docs, but it never happened so here is my version. 

Also, I would welcome a HasOneBy alias which basically does what belongsTo does. It would have saved me days...

**Comment by JasonLandbridge** [comment]
I now finally get what [One-to-One-Inverse](https://vuex-orm.github.io/vuex-orm/guide/model/relationships.html#one-to-one-inverse) means, I would definitely change that to a HasOneBy relationship to make it more clear and to keep it consistent with HasManyBy

**Comment by cuebit** [comment]
Thanks for contribution @JasonLandbridge. +1 for the logical reordering of docs.

It's interesting to see your understanding of the docs.

I think a `hasOneBy` utility method is a nice-to-have but it's not a conventional method. It basically is `belongsTo` once you grasp the idea of its usage but I can see why people could get easily confused.

Perhaps it would be beneficial to find a home for more complex examples such as yours – as to avoid overwhelming the docs with uncommon use-cases (without sounding controversial). I appreciate your intentions and I'll delegate to @kiaking to ultimately make a decision on this inclusion.

**Comment by kiaking** [comment]
@JasonLandbridge Thank you for the contribution! I think we could add section under the Has Many By something like `### Has Many By Inverse` similar to `One To One Inverse`. What do you think?

I just think having section for the relationship that actually doesn't exist, would make people confusing 😓

**Comment by kiaking** [comment]
I'll be closing this PR for now due to inactivity. Please feel free to open another one if you need!

**Pull request closed without merging**
