### PR TITLE
Return empty array on empty to-many relations

### PR DESCRIPTION
**Pull request by timoschwarzer**
PR for #66

### CODE REVIEW

**Comment by kiaking** [comment]
Damn, the conflict. It's only with build files so there wouldn't be any problem but I don't know how to fix this PR from my side... Could you kindly rebase to the current master and push 😢 ?

**Comment by timoschwarzer** [comment]
I'll rebase in a few minutes! :wink:
Have you planned to make a release when this is merged?

**Comment by timoschwarzer** [comment]
@kiaking Ready to merge!

**Comment by kiaking** [comment]
> Have you planned to make a release when this is merged?

Yeah, I'm ready with release note as well : )

Thanks for the fix! Fantastic.

**Pull request merged**
