### PR TITLE
#73 Add `insertOrUpdate` action

### PR DESCRIPTION
**Pull request by iNaD**
This is my first implementation of the `insertOrUpdate` action (see #73). I tried to find all locations where it has to be added, but I think – looking at the tests – that I covered all places.

The `insertOrUpdate` method is currently a bit blown up, maybe I could split it up in some sub routines tomorrow to make it more readable.

### CODE REVIEW

**Comment by iNaD** [comment]
Currently I'm thinking where the documentation of this action would fit best. `docs/store/insertings-and-updating-data.md` seems to be the right place. But should it be a subitem of `## Inserts` or right after it at the same hierarchical level?

**Comment by kiaking** [comment]
Wow! Thank you for the great work! I think test is covering all the place it needs too.

> The insertOrUpdate method is currently a bit blown up, maybe I could split it up in some sub routines tomorrow to make it more readable.

I haven't thought through enough, but maybe it would be easier if `update` method returns updated object and `insertOrUpdate` method can use that returned object to construct return data. Not sure. If we're going to take that path, we can do that after merging this PR though.

> Currently I'm thinking where the documentation of this action would fit best. docs/store/insertings-and-updating-data.md seems to be the right place. But should it be a subitem of ## Inserts or right after it at the same hierarchical level?

Ah, maybe at the same hierarchical level? I don't have any strong opinion for this so you could decide : )

**Comment by iNaD** [comment]
So I added some comments to the method for better understanding what is done. Also removed some useless code which is already covered by the spread operator.

And I added the Documentation for insertOrUpdate 🎉 

To make `update` return the updated records we should open a new PR. After merging that feature I could revise the `insertOrUpdate` action and maybe simplify it even more.

**Comment by kiaking** [comment]
Wonderful! Thanks! I agree with `update` return feature. It should be a separated PR. So I'll merge this one now and release the new version!

Again, thank you for the great work!

**Pull request merged**
