### PR TITLE
Fix Querying issues

### LINKED ISSUE #391: fix: willAll or withAllRecursive throws
if you have a Role model with the following data:
```js
[{
    'id':           1,
    'name':          'Superuser',
    'user_ids':      [5,4,1],
    'users':         [],
}, { 
    'id':           2,
    'name':          'Head Of Department',
    'user_ids':      null,
    'users':         [],
}, {
    'id':            3,
    'name':          'Admin',
    'user_ids':      [4],
    'users':         [],
}, {
    'id':           4,
    'name':          'State Accountant',
    'user_ids':      null,
    'users':         [],
}];
```

running the following:
```js
Role.query().withAll().get()
// or 
Role.query().withAllRecursive().get()
```

throws the following error: 

```js
vuex-orm.esm.js?0937:1354 Uncaught TypeError: Cannot read property 'reduce' of null
    at HasManyBy.getRelatedRecords (vuex-orm.esm.js?0937:1354)
    at eval (vuex-orm.esm.js?0937:1336)
    at Array.forEach (<anonymous>)
    at HasManyBy.load (vuex-orm.esm.js?0937:1335)
    at Function.Loader.eagerLoadRelations (vuex-orm.esm.js?0937:3535)
    at Query.collect (vuex-orm.esm.js?0937:4379)
    at Query.get (vuex-orm.esm.js?0937:4048)
    at HasManyBy.load (vuex-orm.esm.js?0937:1334)
    at Function.Loader.eagerLoadRelations (vuex-orm.esm.js?0937:3535)
    at Query.collect (vuex-orm.esm.js?0937:4379)
```

The reason being that there are records that don't have `user_ids` for their relationships.

### PR DESCRIPTION
**Pull request by emahuni**
closes #391 
closes #390

### CODE REVIEW

**Comment by kiaking** [comment]
@emahuni Thank you so much for the PR! Is't possible for you to add test cases on this one?

**Comment by emahuni** [comment]
> @emahuni Thank you so much for the PR! Is't possible for you to add test cases on this one?

Hi. I did, but I am getting these funny errors in tests that are not happening in my project. So maybe it has something to do with model definitions or something, so I decided to do the PR without the tests. But it works in the project I used it in without any errors. Sorry have a deadline that's on my tail so I couldn't work it in time.

The test is testing ```js Model.query().withAll().get()``` and ```js Model.query().withAllRecursive().get()```, but with one relationship missing in the data.

Let me do a PR with the test, maybe you can figure out why I am getting errors in the test.

**Comment by emahuni** [comment]
Check out the commit file `test/feature/relations/Retrieve_With.spec.js` when yarn test is run the two tests fail, not because of the fix, but there's something I am doing wrong in defining the tests I think. Just don't have enough time right now. sorry.

**Comment by kiaking** [comment]
Thanks! OK, I'll look into this.

**Comment by kiaking** [comment]
@emahuni Hi! So sorry but I just can't get working with PR coming from fork repo... Toe make this PR clean, could you rebase it on master branch and then remove /dist files from the commit?

**Comment by kiaking** [comment]
OK, I'll be resolving #391 at different PR with same code as yours. Then, I'll come back to the other one.

**Comment by emahuni** [comment]
Sorry guys, I have been under the bus for a long time now 😅, deadlines deadlines deadlines

**Comment by kiaking** [comment]
@emahuni Thanks for the heads up! I've actually fixed #391 with another PR. Maybe we can #390 fix with another PR. Do you mind if I close this one for now?

**Pull request closed without merging**
