### PR TITLE
feat: save method to model class

### PR DESCRIPTION
**Pull request by kkyouhei**
fix: https://github.com/vuex-orm/vuex-orm/issues/150

@kiaking 
I write the test code on the weekend.
Please teach if have better code or this have problem this code.

### CODE REVIEW

**Comment by kiaking** [comment]
@kkyouhei Thank you so much! Well done. I think it couldn't be simpler 😃  There's 1 things I would like to discuss.

It's maybe intended but this is going to save all relationships as well. I think we should only save the current model data?

```ts
$save (): Model {
  const fields = this.$fields()
  const record = Object.keys(fields).reduce((record, key) => {
    // Do not include relationships.
    if (field[key] instanceof Attributes.Type) {
      record[key] = this[key]
    }

    return record
  }, {} as Record)

  this.$dispatch('insertOrUpdate', { data: record }).catch((err) => {
    throw err
  })
  return this
}
```

**Comment by kkyouhei** [comment]
I will fix conflict !

**Comment by kkyouhei** [comment]
@kiaking 
hello.

I created save method.
please review.
Do I need put together some commits ? because this PR include useless commits .

**Comment by kiaking** [comment]
Thanks! Wonderful job! Thank you so much for the PR. I'll merge this, add documentation and release it.

> Do I should put together some commits? because this PR include useless commits.

Nah, I think it's OK. I'll just merge it as is.

**Pull request merged**
