### PR TITLE
[WIP] feat(model): enable passing data to persistent methods (#554)

### PR DESCRIPTION
**Pull request by cuebit**
### Description

This PR enables passing data directly to persistent methods, removing the need of `data` key. Subsequently allowing for additional options to be passed as the second argument.

#### Type of PR:

- [ ] Bugfix
- [x] Feature
- [x] Enhancement
- [ ] Documentation
- [ ] Other

#### Breaking changes:

- [x] No
- [ ] Yes

#### Todo:

- [ ] add: deprecation warnings
- [ ] docs: to be updated accordingly
- [x] test: unit tests should apply new style
- [x] test: preserve module tests to ensure module API syntax

### Details

The `Model` methods impacted are as follows [`static`, `instance`]:

- `create`, `$create`
- `insert`, `$insert`
- `update`, `$update`
- `insertOrUpdate`, `$insertOrUpdate`

All methods accept data as the first argument, and any options that previously accompanied the `data` key may be passed as the second argument.

### Examples

Data may be passed directly to any of the aforementioned methods as object literal or array:

```js
User.create({ id: 1, name: 'John Doe' })

User.insert([
  { id: 2, name: 'Jane Doe' },
  { id: 3, name: 'Johnny Doe' }
])
```

Options may be passed as the second argument:

```js
User.update({ name: 'Johnny Doe' }, { where: 1 })
```

Persist options may also be passed as second argument:

```js
const users = {
  id: 1,
  name: 'John Doe',
  roles: [
    { id: 1 title: 'Admin' }
  ]
  posts: [
    { id: 1, title: 'Lorem ipsum' }
  ]
}

User.create(users, {
  insertOrUpdate: ['roles'],
  insert: ['posts']
})
```

Instance methods follow suit:

```js
const user = User.find(1)

user.$update({ name: 'Johnny Doe' })

user.$insert({ id: 2, 'Jane Doe' })
```

Maintains closure support:

```js
User.insert({ id: 1, name: 'John Doe' })

User.update(
  (record) => {
    record.name = 'Jane Doe'
    record.posts.push({ id: 2, title: 'Lorem ipsum' })
  },
  {
    where: (record) => record.id === 1
  }
)
```

### Important

- Module actions should still use the `data` key along with any other persist options.
- Use of `data` key with the aforementioned `Model` methods will warn users of impending deprecation.
- The `data` key option in the aforementioned `Model` methods will be removed in a subsequent major release.

### CODE REVIEW

**Comment by cuebit** [comment]
@kiaking what’s the best way to move forward with this? I’m confident the changes won’t affect existing users, it’s a pretty robust setup.

I’m hesitant in adding documentation until this is merged into dev.

What are your thoughts on deprecation warnings? I’m not sure users will want to see their console flooded with deprecation warnings, though we could create a logger to prevent deprecation warnings appear more than once. Or do you think adding a warning in the change log and release is sufficient?

**Comment by kiaking** [comment]
> What are your thoughts on deprecation warnings? I’m not sure users will want to see their console flooded with deprecation warnings, though we could create a logger to prevent deprecation warnings appear more than once.

Very good point. Wasn't thinking that much. I think at first "adding a warning in the change log and release" should be fine. Since we shouldn't be removing the current behavior at v1.0.0.

> though we could create a logger to prevent deprecation warnings appear more than once.

Yeah maybe we could implement log option feature so users can suppress stuff. But it should definitely be in PR.

---

I think it would be OK to merge this one! If there's nothing to add on your side, let's merge it (and I'll wait until I merge current master branch back to dev with that giant code style change 😅 )

**Comment by cuebit** [comment]
@kiaking nothing to add, I think development on this PR is now stale. I’m happy if you’re happy with it. 

Once merged I can open a new PR for documentation in future we can create a PR for deprecation warnings closer to its removal. Does that sound like a better compromise?

**Comment by kiaking** [comment]
> Once merged I can open a new PR for documentation and in future we can create a PR for deprecation warnings closer to its removal. Does that sound like a better compromise?

Yes, I like it! 👍 

OK, here we go!

**Pull request merged**
