### PR TITLE
Http module

### PR DESCRIPTION
**Pull request by ruddenchaux**
Added a http (axios) module for comunicate with a api server (maybe REST). The goal is to have the vuex store syncronized with the api server based on configurations. So: 

- i have created a new Model class that extend the BaseModel class
- i have created a new ModelConf class for handle the needed configurations
- i have created a new Options class for handle the plugin install options
- i have created a new Http class that use Axios for handle the api server comunication
- i didn't created a test
- i didn't created a documentation

### CODE REVIEW

**Comment by kiaking** [comment]
Hi! Sorry for my late reply and Wow, thank you for the hard work! Could you remove `lib` and `dist` folder from the commit? Those are not meant be committed, and also currently it is a bit hard to grasp the diffs.

**Comment by ruddenchaux** [comment]
Hi Kia, thankyou. You have make a great work, not me:
- I'll open a issue for have the model's schema in the ide's autocomplete
  - Add a field declaration as a model property
  - Or create an ide extension

If you want, I can open a pull request on the **vuex-orm-example** repository to see the http extension at work.

**Comment by ruddenchaux** [comment]
Hi, 
- i have commit some fix to master
- in the fork https://github.com/ruddenchaux/vuex-orm-examples you find the http extension at work

**Comment by KaniRobinson** [comment]
@ruddenchaux @kiaking will this be added to the source code?

**Comment by kiaking** [comment]
@KaniRobinson Sorry for taking long on this PR but I have to look this into more deeper. But, I think we should move this to be as plugin since this is adding `axios` as a dependencies.

So this is more of a `vuex-orm-axios` kinda stuff I guess. Which is really cool! But I think it would suit more as a plugin for this purpose :/

**Comment by KaniRobinson** [comment]
@kiaking, I was thinking the exact same thing, I think you should pass the axios config similarly to how Nuxt handles it, that would be awesome

**Comment by KaniRobinson** [comment]
@kiaking similar to https://github.com/zhouchang2017/vuetify-ts-start/tree/4e376bf7d426f061761a8c2626fa69dd991a21c8/src/vuex-orm-http

**Comment by kiaking** [comment]
Wow you've got pretty much interface for this 😃  I should take time to think about this feature more but just not being able to do it :/

**Comment by KaniRobinson** [comment]
@kiaking if you're interested in collaborating on building a HTTP plugin, ping me a message on twitter https://twitter.com/kanitrobinson

**Comment by kiaking** [comment]
@ruddenchaux Hi! Thank you so much for your hard work and sorry for not responding to this for long time. Now the http module is created as [Plugin Axios](https://github.com/vuex-orm/plugin-axios). It is different from your implementation and it is still very early stage so there's lot to cover from here.

However, I would like to proceed things at plugin-axios and I'll close this PR for this time.

Again, thank you so much for your love and hard work put into this. I appreciate a lot and huge thanks to this PR.

**Comment by ruddenchaux** [comment]
@kiaking hi, thank you. I have many work in this time, however i will happy to contribute in the https://github.com/vuex-orm/plugin-axios.

**Comment by kiaking** [comment]
@ruddenchaux Thank you so much for your kind word! The contribution is heavily welcome and thank you so much for your hard work!

**Pull request closed without merging**
