### PR TITLE
#460 STI relations should be instantiated with the appropriate class

### PR DESCRIPTION
**Pull request by SzNagyMisu**
Issue #460

I have provided the failing tests and made them pass.
I have some refactoring ideas in my mind but I wanted to discuss them first:

1. I made the modification **once for each** _single_ relation class and **once for all** _multiple_ relation classes, because _multiple_ relations had the helper method `makeManyRelation` defined in the superclass `Relation`. _Single_ relations have no such method - I think they could have one called `makeOneRelation`.
    * also I have written the tests accordingly: one test for **all** _multiple_ relations, and one for **each** _single_ relations - I may add tests for **each** _multiple_ relations.
2. It might make sense to define subclasses `SingleRelation` and `MultipleRelation` and set them as superclasses of each concrete relation class. It would make the hierarhcy more reasonable (for example _single_ relation instances wouldn't have to respond to the method `makeManyRelation` and vice versa)

### CODE REVIEW

**Comment by kiaking** [comment]
@SzNagyMisu Thank you so much for the awesome PR!

> 1. I made the modification once for each single relation class and once for all multiple relation classes, because multiple relations had the helper method makeManyRelation defined in the superclass Relation. Single relations have no such method - I think they could have one called makeOneRelation.

Yeah I agree. I don't know why I didn't. Would you like to add one on this PR?

> 2. It might make sense to define subclasses SingleRelation and MultipleRelation and set them as superclasses of each concrete relation class. It would make the hierarhcy more reasonable (for example single relation instances wouldn't have to respond to the method makeManyRelation and vice versa)

Yeah this is tough one too. I've also thought about it. However, the relationship could be bit more complicated than one or many, and I wasn't that sure if it'd a good to way to split them. If there was a mixin or a trait in JS, I would be using those though... (why is thee no mixin in JS? seriously!?)

But maybe yeah, it might make sense. But I would say lets keep it to for now. With future implementation, maybe there will more edge cases. What do you think?

**Comment by SzNagyMisu** [comment]
@kiaking Thanks for the quick reply!

> Yeah I agree. I don't know why I didn't. Would you like to add one on this PR?

Gladly :smiley:

> But I would say lets keep it to for now. With future implementation, maybe there will more edge cases. What do you think?

I understand the reasons and it's all right for me.

Also, what do you think about the tests: having refactored the code with the `makeOneRelation` method defined in `Relation`, should I cut the tests to check just **one** _single_ and **one** _multiple_ relation case? Or should I extend them to contain all? Or just leave them like this?

**Comment by kiaking** [comment]
@SzNagyMisu

Great! Thanks!

> Also, what do you think about the tests: having refactored the code with the makeOneRelationmethod defined in Relation, should I cut the tests to check just one single and one multiple relation case? Or should I extend them to contain all? Or just leave them like this?

I think cutting tests to have one single case is fine for now, as long as test coverage remains 100%!

**Comment by SzNagyMisu** [comment]
Also - I'm not an expert with TypeScript -, shouldn't `Relation` define an abstract method for `make`?

**Comment by SzNagyMisu** [comment]
So, I kept `belongsTo` and `morphTo` also because it has a bit of special logic.

**Comment by kiaking** [comment]
@SzNagyMisu Thanks for the fixes!

> Also - I'm not an expert with TypeScript -, shouldn't Relation define an abstract method for make?

Ah yes! Would you mind adding it? I don't know why it sin't there... If you get trouble adding it because of typings, you can leave it as is. I'll add it after merging the PR 🤝 

> So, I kept belongsTo and morphTo also because it has a bit of special logic.

Wonderful! Thanks so much 👍

**Comment by SzNagyMisu** [comment]
> Ah yes! Would you mind adding it?

I'll give it a try :smiley:

**Comment by kiaking** [comment]
❤️ ❤️ ❤️

**Comment by kiaking** [comment]
@SzNagyMisu Niiiiceeee. Is it ready to be merged? Or are there anything you would still like to add?

**Comment by SzNagyMisu** [comment]
No, I'm done with it. Thanks for the opportunity!

**Comment by kiaking** [comment]
Wonderful! I'll merge this soon and make a new release 👍

**Pull request merged**
