### PR TITLE
Allow users to granularly define which properties to insert or to create

### PR DESCRIPTION
**Pull request by timoschwarzer**
I had the following scenario:

Imagine you have three models: Model1, Model2 and User.
Model1 and Model2 have a `belongsTo(User, ...)`-attribute.

Everytime a user opens the website, I fetch all Model1 and Model2 instances from the server and use the `create` action to insert them into the ORM. (e.g. `store.dispatch('entities/model1/create', { data: dataFromServer })`).

This works fine until I try to do that with Model2, because the `create` action on Model2 will override the Users from Model1.

This PR adds an `subresourceMethod` property to the `create` action.

```javascript
store.dispatch('entities/model2/create', {
  data: response.data,
  subresourceMethod: 'insert'
});
```
This will use `create` on the Model2 model and `insert` on all related models.

Maybe this should be discussed and when there is a final prototype, tests should be written.

### To do
- [ ] Update code
- [ ] Update docs
- [ ] Write tests

## Notices
- The old `Repo.save()` has been renamed to `Repo.persist()`

### CODE REVIEW

**Comment by kiaking** [comment]
Oh well yeah, you got a good point. This is a pitfall. Thank you so much for your PR!

Maybe we would want to have a more flexible way of handling this? For instance, when saving multi related data, such contains user, posts, and comments, and want to `create` user and post but want to `insert` comments.

One idea came to me is to create a new generic method like `save` or `add` and pass `create` and `insert` option with the relationship.

```js
// `create` users and posts but `insert` comments.
store.dispatch('entities/users/save', {
  data: response.data,
  create: ['users', 'posts'],
  insert: ['comments']
})
```

Then we can use this method underneath and add similar option to `create` and `insert` as well.

```js
store.dispatch('entities/users/create', {
  data: response.data,
  insert: ['comments']
})

store.dispatch('entities/users/insert', {
  data: response.data,
  create: ['posts']
})
```

What do you think?

**Comment by timoschwarzer** [comment]
Yes, I really like this `save` thing!

**Comment by kiaking** [comment]
Great! Do you want work on with this PR? I could tackle this when I finish up my many to many relationship I'm currently working on : )

**Comment by timoschwarzer** [comment]
Will do so! :smile:

**Comment by kiaking** [comment]
Yeah 🍺

**Comment by timoschwarzer** [comment]
I will open a new PR for this because I forgot to create a new branch... :man_facepalming:

**Comment by kiaking** [comment]
😃

**Comment by kiaking** [comment]
By the way, good method name `persist`. I love it.

**Comment by timoschwarzer** [comment]
Follow-up: #67

**Pull request closed without merging**
