### PR TITLE
Implement withAll and withAllRecursive methods

### LINKED ISSUE #103: Add `withAll` method that retrieve all relations
Raised from #94. It would be nice to have method like `withAll` that will load all of the relation at once.

```js
store.getters['entities/users/query']().withAll().get()
```

### PR DESCRIPTION
**Pull request by timoschwarzer**
Closes #103

### CODE REVIEW

**Comment by timoschwarzer** [comment]
This should be ready to merge now.

**Comment by timoschwarzer** [comment]
Whoah, getting confused with words :rofl:

**Comment by kiaking** [comment]
Oh man this is super cool. The withRecursive is slick idea. Well done!!!

Thank you so much for your great work!

**Comment by timoschwarzer** [comment]
Thank you for this great library! :grinning:

**Pull request merged**
