### PR TITLE
morphToMany relation duplicates the pivot records

### PR DESCRIPTION
**Pull request by kkyouhei**
fix: https://github.com/vuex-orm/vuex-orm/issues/258

Hi @kiaking 

Cause is this.increment() to Taggable's id field, but I don't know is need to fix this problem, because pivot data isn't set to insertOrUpdate.

### CODE REVIEW

**Comment by kiaking** [comment]
Thank you so much for the test case! I think it should be fixed...? It should create intermediate pivot data during the data creation. Or if it doesn't fail if Taggable didn't have `this.increment` then it should work with `increment` as well. I think.

**Comment by kiaking** [comment]
Niiice thanks!

**Comment by kkyouhei** [comment]
Hi @kiaking 
I fixed. please review.

**Comment by kiaking** [comment]
Wonderful!!! Thank you so much! Looking good to me. I'll merge this and release the new version soon!

**Pull request merged**
