### PR TITLE
Ignore create pivot record

### PR DESCRIPTION
**Pull request by kkyouhei**
fix: https://github.com/vuex-orm/vuex-orm/issues/201

I will fix broken testcode.

### CODE REVIEW

**Comment by kiaking** [comment]
Wow great! Thanks! I'll be waiting for the fix 👍

**Comment by kkyouhei** [comment]
@kiaking 
This pull request not create pivot table record if not set parentKey relatedKey .
I am concerned that vuex-orm-graphql will not work with this modify.

**Comment by kiaking** [comment]
@kkyouhei Thank you so much! I'll check if that impact with grapnel plugin.

@phortx Could you take a look at this and see if it's safe to implement this?

**Comment by kiaking** [comment]
@phortx Thank you very much! I'll merge this soon and make a release!

**Comment by kkyouhei** [comment]
@phortx Thank you very much!

**Pull request merged**
