### PR TITLE
feat(Attribute): add `hasOneThrough` relation type

### PR DESCRIPTION
**Pull request by cuebit**
This PR introduces a model attribute to support _has-one-through_ relations.

See discussion thread #611.

#### Type of PR:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Documentation
- [ ] Other, please describe:

#### Breaking changes:

- [x] No
- [ ] Yes

#### TODO

- [x] Feature Tests
- [x] Performance Tests
- [x] Documentation

### Details

Adds a new model attribute `hasOneThrough` which mimics the principles offered by the `hasManyThrough` but configured with a single-relation schema.

### CODE REVIEW

**Comment by cuebit** [comment]
@kiaking before I add documentation could you review and let me know if there's anything you may want to add to this?

**Comment by kiaking** [comment]
@cuebit Hey so sorry for the conflict on index file. Though this looks perfect 👍  Can you rebase it on the latest dev branch?

**Comment by cuebit** [comment]
Done. Could this be squashed into one commit and use the title of the pull request as the commit message?

**Comment by kiaking** [comment]
> Done. Could this be squashed into one commit and use the title of the pull request as the commit message?

Yap! Seems like that's how conventional commit works 👍

**Comment by cuebit** [comment]
Should we promote this method of merging in future then? I wasn’t completely aware of how you actually merge PR’s but given that I mistakenly rebased the branch in itself I didn’t want to pollute the git log and also keep to the conventional commit scheme.

**Comment by kiaking** [comment]
> Should we promote this method of merging in future then?

Yes we should. I was about to tell you I forgot to do it :p

**Pull request merged**
